version: 2

models:
  - name: intermediate_dhis_moh_505_wide_to_long
    description: This table contains preprocessed MOH 505 data that has been transformed from wide format to long format
    columns:
      - name: age_group
        description: Age group category
        tests:
          - accepted_values:
             values: ['< 5 years', '>= 5 years']  
      - name: sub_county
        description: Sub county of reporting
        tests:
          - not_null
      - name: county
        description: County of reporting
        tests:
          - not_null
      - name: indicator
        description: Name of indicator being reported
        tests:
          - not_null
  - name: intermediate_dhis_moh_505_mappings
    description: This table contains preprocessed MOH 505 data that contains mappings of internal indicator and  disease list to the external MOH 505 indicators
    columns:
      - name: age_group
        description: Age group category
        tests:
          - accepted_values:
             values: ['< 5 years', '>= 5 years'] 
      - name: sub_county
        description: Sub county of reporting
        tests:
          - not_null
      - name: county
        description: County of reporting
        tests:
          - not_null
      - name: indicator
        description: Name of indicator being reported
        tests:
          - not_null
      - name: indicator_value
        description: Value of indicator being reported
        tests:
          - not_null
      - name: disease
        description: Disease being reported
        tests: 
          - not_null