version: 2

models:
  - name: aggregate_moh_505_report
    description: This table has aggregate data for various diseases' indicator as reported on the DHIS MOH 505 report
    columns:
      - name: disease
        description: Name of disease being reported
        tests:
          - not_null
      - name: gender
        description: Gender of cases reported
        tests:
          - not_null
          - accepted_values:
             values: ['Female', 'Male', 'unset']
      - name: age_group_category
        description: Age group categorization of under five years or over five year
        tests:
          - accepted_values:
             values: ['< 5 years', '>= 5 years', 'unset']  
          - not_null:
              where: "indicator_description not in ('CSF -Typed HiB','Bacterial Meningitis +ve Sp','CSF -Typed +ve NmA','Bacterial Meningitis No Contaminated','Bacterial Meningitis +ve H Influenza','CSF -Type Indeterminate','CSF -Typed +ve NmX','Bacterial Meningitis +ve Nm','Dysentery <5 yrs, Cases','CSF -Typed +ve NmC','Bacterial Meningitis No Tested','Bacterial Meningitis No CSF','CSF -Typed +ve NmW 135','CSF -Typed +ve NmB')"
      - name: epi_week
        description: EPI week of the report
        tests:
          - not_null
      - name: year         
        description: Year of the report
        tests:
          - not_null
      - name: county         
        description: County where data was reported for
        tests:
          - not_null
      - name: facility_name       
        description: Facility where data was reported for
        tests:
          - not_null
      - name: indicator_description     
        description: Indicator name being reported
        tests:
          - not_null
      - name: indicator_value      
        description: Indicator name being reported
        tests:
          - not_null