dmi_dbt:
  target: dev
  outputs:
    dev:
      type: sqlserver
      driver: 'ODBC Driver 17 for SQL Server'
      server: "{{env_var('DBT_SERVER')}}"
      port: 8912
      database: "{{env_var('DBT_DATABASE')}}"
      schema: dbo
      user:  "{{env_var('DBT_USER')}}"
      password: "{{env_var('DBT_PASSWORD')}}"
      trust_cert: true
      threads: 24
    prod:
      type: sqlserver
      driver: 'ODBC Driver 17 for SQL Server'
      server: "{{env_var('DBT_SERVER')}}"
      port: 8912
      database: "{{env_var('DBT_DATABASE')}}"
      schema: dbo
      user:  "{{env_var('DBT_USER')}}"
      password: "{{env_var('DBT_PASSWORD')}}"
      trust_cert: true
      threads: 24