dmi_dbt:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{env_var('DBT_SERVER')}}"
      database: "{{env_var('DBT_DATABASE')}}"
      schema: "{{env_var('DBT_SCHEMA')}}"
      port: 8988
      user:  "{{env_var('DBT_USER')}}"
      password: "{{env_var('DBT_PASSWORD')}}"
      threads: 4
    prod:
      type: postgres
      host: "{{env_var('DBT_SERVER')}}"
      database: "{{env_var('DBT_DATABASE')}}"
      schema: "{{env_var('DBT_SCHEMA')}}"
      port: 8988
      user:  "{{env_var('DBT_USER')}}"
      password: "{{env_var('DBT_PASSWORD')}}"
      threads: 4