name: Deploy SHIELD dbt

on:
  schedule:
    - cron: '* * * * *'

env:
  DBT_SERVER: ${{ secrets.DBT_SERVER }}
  DBT_PORT: ${{ secrets.DBT_PORT }}
  DBT_USER: ${{ secrets.DBT_USER }}
  DBT_PASSWORD: ${{ secrets.DBT_PASSWORD }}
  DBT_DATABASE: ${{ secrets.DBT_DATABASE }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install dbt-sqlserver
          dbt deps --profiles-dir ./profiles/ --target dev
          
      - name: Run dbt
        run: |
          dbt run --profiles-dir ./profiles/ --target dev
      
          
