version: 2
sources:
  - name: central_raw_sari_ili
    database: SHIELD
    schema: central_raw_sari_ili
    tables:
      - name: sari_ili_data
        description: This table contains raw data for SARI-ILI
  - name: central_raw_khis
    database: SHIELD
    schema: central_raw_khis
    tables:
      - name: moh_505
        description: This table contains raw data for MOH 505 form
  - name: central_raw_mdharura
    database: SHIELD
    schema: central_raw_mdharura
    tables:
      - name: mdharura_ebs_linelist
        description: This table contains raw data for M-dharura app
      - name: mdharura_ebs_aggregate
        description: This table contains raw aggregate data for M-dharura app