version: 2
sources:
  - name: central_raw_sari_ili
    database: SHIELD
    schema: central_raw_sari_ili
    tables:
      - name: sari_ili_data
        description: This table contains raw data for SARI-ILI
  - name: central_raw_dhis
    database: SHIELD
    schema: central_raw_dhis
    tables:
      - name: moh_505
        description: This table contains raw data for moh_505 form
  - name: central_raw_mdharura
    database: SHIELD
    schema: central_raw_mdharura
    tables:
      - name: mdharura_ebs_linelist
        description: This table contains raw data for M-dharura app