version: 2
sources:
  - name: central_raw_sari_ili
    database: central_raw_sari_ili
    schema: dbo
    tables:
      - name: SARI_ILI_data
        description: This table contains raw data for SARI-ILI
  - name: central_raw_dhis
    database: central_raw_dhis
    schema: dbo
    tables:
      - name: moh_505
        description: This table contains raw data for moh_505 form
  - name: central_raw_mdharura
    database: central_raw_mdharura
    schema: dbo
    tables:
      - name: mdharura_ebs_linelist
        description: This table contains raw data for M-dharura app